config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :movies
  devise_for :users
  get 'home/index'

  get 'bookings/index/:movie_id', to: "bookings#index", as: :booking_home
  post 'bookings/create', to: "bookings#create"
  get 'bookings/invoice/:booking_id', to: "bookings#invoice", as: :bookings_invoice
  get "show_booked_seats", to: "bookings#show_booked_seats"
  match "export_report", to: "reports#export_report", via: [:get, :post]
  get "reports", to: "reports#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :movie
	has_many :seats
end

app/models/movie.rb
class Movie < ApplicationRecord
	has_many :bookings
end

app/models/seat.rb
class Seat < ApplicationRecord
	belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
  	@booking = Booking.new
  	@movie = Movie.find_by_id(params[:movie_id])
  end

  def create
  	booking_hash = params["booking"]
  	booking = Booking.create(movie_id: booking_hash["movie_id"], timeslot: booking_hash["timeslot"])
  	respond_to do |format|
      if booking.save
      	create_seats booking, booking_hash
        format.html { redirect_to bookings_invoice_path(booking.id), notice: 'Booking was successfully created.' }
      end
    end
  end

  def create_seats booking, booking_hash
  	booking_hash["selected_seats"].each do |k, v|
  		v.each do |seat_no|
  			Seat.create(booking_id: booking.id, seat_no: seat_no, price: k.to_i)
  		end
  	end
  end

  def show_booked_seats
  	@booked_seats = Booking.joins('RIGHT JOIN seats ON seats.booking_id = bookings.id').select("seats.price, seats.seat_no").where(timeslot: params['timeslot'], movie_id: params['movie_id'])
  	if request.xhr?
  	end
  end

  def invoice
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
  def index
  	@movies = Movie.all
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :description, :timeslot)
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	before_action :authenticate_user!
	def index
	end

	def export_report
		require "csv" 
		file = "#{Rails.root}/report.csv" 
		bookings = Booking.joins('RIGHT JOIN seats ON seats.booking_id = bookings.id').select("seats.price, seats.seat_no, bookings.created_at, bookings.updated_at").where(timeslot: params['timeslot'], movie_id: params['movie_id'])
		movie = Movie.find params['movie_id']
		price, counter, seat_150, seat_200, seat_300 = 0, 0, 0, 0, 0
		CSV.open(file, "wb") do |row|
		  row << ["Movie Name", "Time Slot", "Seat No", "Seat Price", "Create Date", "Updated Date"]
		  bookings.each do |o|
		     row << [movie.name, params['timeslot'], o.seat_no, o.price, o.created_at, o.updated_at]
		     price = price + o.price
		     counter = counter + 1
		     if o.price.eql? 150
		     	seat_150 = seat_150 + 1
		     elsif o.price.eql? 200
		     	seat_200 = seat_200 + 1
		     else
		     	seat_300 = seat_300 + 1
		     end
		     		
		  end
		  row << []

		  row << ['Seats ', "Total Seats" , "Total Price", '', '', '']
		  row << ['Seats Booked for 150 ', seat_150 , 150*seat_150, '', '', '']
		  row << ['Seats Booked for 200 ', seat_200 , 200*seat_200, '', '', '']
		  row << ['Seats Booked for 300 ', seat_300 , 300*seat_300, '', '', '']
		  row << ['Total Seats Booked ', counter , '', '', '', '']
		  row << ['', 'Total Collection', price , '', '', '']
		end
		File.open(file, 'r') do |f|
		  send_data f.read, :type => "text/csv", :filename => "report.csv"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
	def find_seats_by_booking_id booking_id
		Seat.where(:booking_id=> booking_id)
	end

	def find_booking_by_booking_id booking_id
		booking = Booking.find booking_id
		booking_time = booking.timeslot
		movie_name = booking.movie.name
		return booking_time, movie_name 
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookings/_seats.html.erb
<fieldset> 
	<legend>Lower - Rs 150/- </legend>
	<div class="field">
	<%  counter = 0 %>
	<% for i in 1..30 %>
		<span>
			<span style="position: relative;left: 40px;bottom: 20px;"> <%= i %> </span>
			<input type="checkbox" name="booking[selected_seats][150][]" value="<%= i %>" class="selected_seats_150_<%= i %>" style="height: 50px;width: 50px"/>
		</span>
		<%  counter = counter + 1 %>
		<% if counter == 10 %>
		<br>
		<% counter = 0 %>
		<% end %>
	<% end %>
	</div>
</fieldset></br>

<fieldset> 
	<legend>Middle - Rs 200/-</legend>
	<div class="field">
	<% for i in 31..70 %>
		<span >
			<span style="position: relative;left: 40px;bottom: 20px;"> <%= i %> </span>
			<input type="checkbox" name="booking[selected_seats][200][]" value="<%= i %>" class="selected_seats_200_<%= i %>" style="height: 50px;width: 50px"/>
		</span>
		<%  counter = counter + 1 %>
		<% if counter == 10 %>
		<br>
		<% counter = 0 %>
		<% end %>
	<% end %>
	</div>
</fieldset></br>

<fieldset> 
	<legend>Upper - Rs 300/-</legend>
	<div class="field">
	<% for i in 71..100 %>
		<span style="">
			<span style="position: relative;left: 40px;bottom: 20px;"> <%= i %> </span>
			<input type="checkbox" name="booking[selected_seats][300][]" value="<%= i %>" class="selected_seats_300_<%= i %>" style="height: 50px;width: 50px">
		</span>
		<%  counter = counter + 1 %>
		<% if counter == 10 %>
		<br>
		<% counter = 0 %>
		<% end %>
	<% end %>
	</div>
</fieldset>

<% @booked_seats.each do |seat| %>
<script type="text/javascript">
	$('.selected_seats_<%= seat.price %>_<%= seat.seat_no %>').prop("disabled", true);
	$('.selected_seats_<%= seat.price %>_<%= seat.seat_no %>').parent().addClass("redBackground");
</script>
<% end %>

app/views/bookings/index.html.erb
<style type="text/css">
	.redBackground{
	/*background-color:red;*/
	}
	.greenBackground{
		/*background-color:red;*/
	}
</style>

  <% if @movie.present? %>
  	<h1><span class="label label-info">Selected Movie: <%= @movie.name %> </span></h1>
  	<% else %>
  	<h1>No Movie Found</h1>
  <% end %>

<%= form_for @booking, url: bookings_create_path, method: :post do |form| %>
  <%= hidden_field_tag "booking[movie_id]", params[:movie_id] %>

  <div class="field">
    <%= form.label :timeslot %>
     <%= form.select(:timeslot, [['Select', ''], [ "12-3"], ["4-7"], ["8-11"]]) %>
  </div>

  <div class="field">
	<div id="seats"></div>
  </div>

  <div class="actions">
    <%= form.submit :class=> "submit-btn btn btn-md btn-success"%>
  </div>
<% end %>

<script type="text/javascript">
	$(".submit-btn").attr('disabled', 'disabled');
	$(function() {
		$("#booking_timeslot").change(function() {
			console.log($(this).val())
			var timeslot = $(this).val();
			var movie_id = $("#booking_movie_id").val();
			if(timeslot != ''){
				$("#seats").show()
				$(".submit-btn").removeAttr('disabled');
				$.ajax({
				    method: "GET",
					url: "/show_booked_seats",
					data: {timeslot: timeslot, movie_id: movie_id},
				    success: function (data,status,xhr) {   // success callback function
				    },
				    error: function (jqXhr, textStatus, errorMessage) { // error callback 
				    }
				});
			}else{
				$("#seats").hide();
				$(".submit-btn").attr('disabled', 'disabled')
			}
		});
	});
</script>

app/views/bookings/invoice.html.erb
	<style type="text/css">
		.tbl-style{width: 100%;}
		.tbl-style  {border-collapse:collapse;border-spacing:0;border-color:#ccc;margin:0px auto;}
		.tbl-style td{font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#fff;}
		.tbl-style th{font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#f0f0f0;}}
		.text-right{text-align: right;}
		.col-6{width: 50%;}
		.col-6{float: left;}
		@media only screen and (max-width : 1024px) {
			.col-md-12{width: 100%;}
		}
		@media only screen and (max-width : 768px) {
			.col-sm-12{width: 100%;}
		}
		@media only screen and (max-width : 700px) {
			.col-xs-12{width: 100%;}
		}
		.text-middle{text-align: center;}
	</style>

	<% booking_time, movie_name = find_booking_by_booking_id(params[:booking_id]) %>
	<% @seats = find_seats_by_booking_id(params[:booking_id]) %>


	<section class="" id="invoice">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<h1 style="text-align: center;">Invoice</h1>
				</div>
			</div>
			<br/>
			<div class="row">
				<div class="col-12">
					<div class="col-6">
						Movie Name : <h3> <%= movie_name %> </h3>
					</div>
					<div class="col-6" style="text-align: right;">
						Movie Time : <h2> <%= booking_time %> </h2>
					</div>
				</div>
			</div>
			</br>
			<div class="row">
				<div class="col-12">
					<table class="tbl-style table">
						<thead>
							<tr>
								<th>Sr. No.</th>
								<th>Seat Numbers</th>
								<th>Amount</th>
							</tr>
						</thead>
						<tbody>
							<% counter, price = 0, 0
							@seats.each do |seat| %>
							<tr class="text-middle">
								<td><%= counter = counter+1 %></td>
								<td><%= seat.seat_no %></td>
								<td><%= seat.price%></td>
								<% price = seat.price + price %>
							</tr>
							<% end %>
							<tr class="text-middle">
								<td colspan="2" style="font-weight: bold;">Amount</td>
								<td style="font-weight: bold;"><%= price %></td>
							</tr>
							
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</section>

app/views/bookings/show_booked_seats.js.erb
$("#seats").html("<%= j render(partial: 'seats') %>");

app/views/home/index.html.erb
<table class="table">
	<thead>
		<th>Name</th>
		<th>Description</th>
		<th>Action</th>
	</thead>
	<% @movies.each do |movie|  %>
	<tbody>
		<tr>
			<td><%= movie.name %></td>
			<td><%= movie.description %></td>
			<td><%= link_to "Book Movie", booking_home_path(movie.id), class: 'btn btn-md btn-warning' %></td>
		</tr>
	</tbody>
	<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieBookingSystem</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
      .footer {
         position: fixed;
         left: 0;
         bottom: 0;
         width: 100%;
         background-color: lightgrey;
         text-align: center;
        }
    </style>
  </head>

  <body>

    <h2 style="text-align: center;"><span class="label label-default">Movie Booking System</span></h2>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div> 
      <%= link_to "Home", home_index_path, class: 'btn btn-success btn-md' %>
    </div>
    <% if user_signed_in? %>
  	  <div style="text-align: right;">
  	   <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-md btn-info") %>
       <%= link_to "Go to Add Movie", movies_path, class: 'btn btn-md btn-success' %>
  	  </div>
  	<% else %>
  	  <div style="text-align: right;">
    	  <%= link_to('Login', new_user_session_path, class: 'btn btn-md btn-info') %>
        <%= link_to "Go to Add Movie", movies_path, class: 'btn btn-md btn-success' %>
  	  </div>
  	<% end %>

    <%= yield %>
    <div class="footer">
      <p>Created by @pradnya-madnaik</p>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :movie_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :movie_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<%= link_to "Go To Report", reports_path, class: 'btn btn-md btn-warning' %>

<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.description %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path, class: 'btn btn-md btn-default' %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/reports/index.html.erb
<%= form_tag('/export_report') do -%>
	  <div class="field">
	  	<%= label_tag "Movie Name : " %>
	  	<%= select_tag "movie_id", options_for_select(Movie.all.collect {|p| [ p.name, p.id ]}) %>
	  </div>

	  <div class="field">
	  	<%= label_tag "Time Slot : " %>
	  	<%= select_tag "timeslot", options_for_select([['Select', ''], [ "12-3"], ["4-7"], ["8-11"]]) %>
	  </div>

	  <div class="field">
	  	<%= label_tag "Date : " %>
	  	<input type="date" name="create_at">
	  </div>

   <%= submit_tag( "Export" , class: 'btn btn-md btn-warning') %>
<% end %>